name: Chrome Web Store Automation

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to the Chrome Web Store
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download release artifact
        run: gh release download ${{ github.event.inputs.release-version || github.event.release.tag_name }} --pattern 'dist.zip'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to the Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}