name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Lint & test
        run: |
          npm ci
          npm run lint
          npm test
      - name: Test & Build Storybook
        run: npm run test-storybook:ci
      - name: Build the artifact
        run: npm run build:release
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-snooze-chrome-extension
          path: dist
      - if: github.ref == 'refs/heads/master'
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
