name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      baseTag:
        description: 'base release tag'
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform/optic-release-automation-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          build-command: |
            npm ci
            npm run update-manifest
            npm run build:release
          artifact-path: dist
